### PR TITLE
Refactor: Change handling and reporting of broken business rules

### PR DESCRIPTION
**Pull request by kft**
## Description
The EDI messaging layer must be able to distinguish between broken business rules in order to generate EDI reject messages with specific error codes.

Instead of returning the entire business rule residing at domain layer, the business rule type is returned in a Result object. Thus, the EDI messaging layer will something type strong to use for distinguishing between different business rules, and does not have to rely  on a unique identifier in form of eg. a string.

Changes in this PR:
- Access modifiers of business rules changed from Public to Internal
- Introduce `ValidationError` to represent a broken business rule
- Refactored `BusinessRulesValidationResult` to include a collection of `ValidationError` instead of the business rules them self.

### CODE REVIEW

**Comment by kft** [comment]
Can we refactor the input validation framework to use same approach ? Currently, the input validation rules contain ebIX specific error codes (eg. E17, E18).

**Review by Korgath — APPROVED** [review]

**Comment by kft** [comment]
Should be rename the `AreAnyBroken` property on the `BusinessRulesValidationResult` to `Success` ? It seem more right to focus on the positive side of things :-) If we do, it will break a fair amount of tests, but the fix is easy I reckon (Assert on True instead of False).

**Review by erduna — APPROVED** [review]

**Comment by cmgrd** [comment]
> Can we refactor the input validation framework to use same approach ? Currently, the input validation rules contain ebIX specific error codes (eg. E17, E18).

I think we should ask the system team about this part. @Sondergaard ?

> Should we rename the AreAnyBroken property on the BusinessRulesValidationResult to Success ? It seem more right to focus on the positive side of things :-) If we do, it will break a fair amount of tests, but the fix is easy I reckon (Assert on True instead of False).

I think (Is)Success is slightly better than AreAnyBroken, so if it's possible to change with minimal effort, then I think we should change it.

**Review by cmgrd — APPROVED** [review]

**Review by erduna — APPROVED** [review]
Is it an issue our business rule currently only supports having a message, while our property rules only support a code as output? They should both support both, but is that blocking for the validationerror class?

**Comment by kft** [comment]
> Is it an issue our business rule currently only supports having a message, while our property rules only support a code as output? They should both support both, but is that blocking for the validationerror class?

We want to avoid defining error/reason codes in both business rules and validation rules, because it is really an EDI message concern. By parsing strong types indicating the types of violated validation and business rules, the EDI messaging layer can use these to determine the correct error codes to include in rejection messages. That is the point of the `Rule` property on `ValidationError`.
We could say the Message property of `IBusinessRule` is irrelevant, because it is actually handled by the EDI messaging layer.

**Pull request merged**
